# Generated by Django 4.2.6 on 2023-10-26 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_attachs_authgroup_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='attachs',
            table='attachs',
        ),
        migrations.AlterModelTable(
            name='boardcontents',
            table='board_contents',
        ),
        migrations.AlterModelTable(
            name='danjis',
            table='danjis',
        ),
        migrations.AlterModelTable(
            name='usergroups',
            table='user_groups',
        ),
    ]
